### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by jotelha**
* Diversified LICENSE with CC-BY-SA applied to data and documents
* Added original icon svgs with attribution note to Michal
* Added rastered icons in different formats
* Included icons in workflows (WIP)
* Template desktop launcher for Ubuntu

### CODE REVIEW

**Review by pastewka — COMMENTED** [review]
Why do you distinguish between large and small logo. I would just make everything e.g. 32x32 and below use the small logo and the rest the large logo.

**Comment by jotelha** [comment]
That's just how the two different svg files have been named, I don't distinguish at all.

**Comment by pastewka** [comment]
The windows build does not seem to complete

**Review by pastewka — APPROVED** [review]

**Comment by jotelha** [comment]
Yes, sorry, should have marked as WIP, queried your review only because I wanted you to have a look at the license & generated icons, not for merging yet.

**Pull request merged**
